# Generated by Django 5.2 on 2025-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='line_color',
            field=models.CharField(choices=[('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зеленый'), ('black', 'Черный'), ('purple', 'Фиолетовый')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='graph',
            name='line_width',
            field=models.FloatField(default=1.0),
        ),
    ]
