# Generated by Django 5.2 on 2025-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graph_line_color_graph_line_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergallery',
            options={'verbose_name_plural': 'User Galleries'},
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='usergallery',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_gallery_title'),
        ),
    ]
