# Generated by Django 5.2 on 2025-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_usergallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
